// ============================================================
// GeneratedWorkout.swift
// Forzee — Core/Models
//
// Represents a workout generated by Kai (KaiEngine.generateWorkout).
// Parsed from Claude's structured JSON response.
// Mapped to the `workouts` table in Supabase before saving.
// ============================================================

import Foundation

// MARK: - GeneratedWorkout

struct GeneratedWorkout: Identifiable, Codable {

    let id: UUID

    // Workout metadata
    var name: String
    var workoutType: String    // strength | cardio | mobility | hiit | recovery
    var estimatedDurationMins: Int

    // Kai's reasoning — shown to the user as a coaching note
    var coachingNote: String?

    // The exercises in order
    var exercises: [WorkoutExercise]

    // Context at time of generation (stored for future AI reference)
    var contextSnapshot: UserContextSnapshot?

    init(
        id: UUID = UUID(),
        name: String,
        workoutType: String,
        estimatedDurationMins: Int,
        coachingNote: String? = nil,
        exercises: [WorkoutExercise],
        contextSnapshot: UserContextSnapshot? = nil
    ) {
        self.id = id
        self.name = name
        self.workoutType = workoutType
        self.estimatedDurationMins = estimatedDurationMins
        self.coachingNote = coachingNote
        self.exercises = exercises
        self.contextSnapshot = contextSnapshot
    }

    // MARK: - Decodable
    //
    // Custom init: Claude's JSON response (see WorkoutGenerationPrompt) never
    // includes an "id" field — it's not something the model should invent —
    // so the auto-synthesized Decodable, which would require it, always
    // failed to decode a real generation. Every other field decodes exactly
    // as auto-synthesis would; only `id` gets a fresh UUID when absent.

    enum CodingKeys: String, CodingKey {
        case id, name, workoutType, estimatedDurationMins, coachingNote, exercises, contextSnapshot
    }

    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        id = try container.decodeIfPresent(UUID.self, forKey: .id) ?? UUID()
        name = try container.decode(String.self, forKey: .name)
        workoutType = try container.decode(String.self, forKey: .workoutType)
        estimatedDurationMins = try container.decode(Int.self, forKey: .estimatedDurationMins)
        coachingNote = try container.decodeIfPresent(String.self, forKey: .coachingNote)
        exercises = try container.decode([WorkoutExercise].self, forKey: .exercises)
        contextSnapshot = try container.decodeIfPresent(UserContextSnapshot.self, forKey: .contextSnapshot)
    }
}

// MARK: - WorkoutExercise

struct WorkoutExercise: Identifiable, Codable {
    let id: UUID
    var exerciseId: String?   // Reference to exercises table (optional — Kai may name new exercises)
    var name: String
    var sets: Int
    var reps: String          // String to support "8-12" ranges
    var weightKg: Double?     // nil = bodyweight or user-determined
    var restSecs: Int
    var notes: String?        // Form cues, modifications, Kai's advice for this exercise

    // Phase 3 "Insights" plumbing — Kai tags these at generation time
    // (WorkoutGenerationPrompt) or extraction time (extract_workout skill).
    // Optional and additive: older stored workouts simply decode nil here,
    // same pattern as restSecs below.
    var primaryMuscleGroup: MuscleGroup?
    var secondaryMuscleGroups: [MuscleGroup]

    init(
        id: UUID = UUID(),
        exerciseId: String? = nil,
        name: String,
        sets: Int,
        reps: String,
        weightKg: Double? = nil,
        restSecs: Int = 90,
        notes: String? = nil,
        primaryMuscleGroup: MuscleGroup? = nil,
        secondaryMuscleGroups: [MuscleGroup] = []
    ) {
        self.id = id
        self.exerciseId = exerciseId
        self.name = name
        self.sets = sets
        self.reps = reps
        self.weightKg = weightKg
        self.restSecs = restSecs
        self.notes = notes
        self.primaryMuscleGroup = primaryMuscleGroup
        self.secondaryMuscleGroups = secondaryMuscleGroups
    }

    // MARK: - Decodable
    //
    // Same reasoning as GeneratedWorkout above — Claude's exercise JSON never
    // includes "id", so it needs a fresh UUID rather than a required field.
    // primaryMuscleGroup/secondaryMuscleGroups are similarly forgiving: an
    // unrecognized or missing tag decodes to nil/empty rather than failing
    // the whole exercise, since Claude occasionally free-names a muscle
    // group not in MuscleGroup's fixed list.

    enum CodingKeys: String, CodingKey {
        case id, exerciseId, name, sets, reps, weightKg, restSecs, notes
        case primaryMuscleGroup, secondaryMuscleGroups
    }

    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        id = try container.decodeIfPresent(UUID.self, forKey: .id) ?? UUID()
        exerciseId = try container.decodeIfPresent(String.self, forKey: .exerciseId)
        name = try container.decode(String.self, forKey: .name)
        sets = try container.decode(Int.self, forKey: .sets)
        reps = try container.decode(String.self, forKey: .reps)
        weightKg = try container.decodeIfPresent(Double.self, forKey: .weightKg)
        restSecs = try container.decodeIfPresent(Int.self, forKey: .restSecs) ?? 90
        notes = try container.decodeIfPresent(String.self, forKey: .notes)
        primaryMuscleGroup = (try? container.decodeIfPresent(MuscleGroup.self, forKey: .primaryMuscleGroup)) ?? nil
        secondaryMuscleGroups = (try? container.decodeIfPresent([MuscleGroup].self, forKey: .secondaryMuscleGroups)) ?? nil ?? []
    }
}

// MARK: - WorkoutParser

/// Parses Kai's structured JSON workout response into a GeneratedWorkout.
enum WorkoutParser {

    /// Parse a raw Claude response string into a GeneratedWorkout.
    /// Claude is instructed to return valid JSON — this extracts and decodes it.
    static func parse(
        response: String,
        userId: String,
        context: UserContextSnapshot
    ) throws -> GeneratedWorkout {
        // Extract JSON block from response (Claude may wrap it in prose)
        let json = extractJSON(from: response)

        guard let data = json.data(using: .utf8) else {
            throw WorkoutParserError.invalidJSON
        }

        let decoder = JSONDecoder()
        decoder.keyDecodingStrategy = .convertFromSnakeCase

        var workout = try decoder.decode(GeneratedWorkout.self, from: data)
        workout = GeneratedWorkout(
            id: workout.id,
            name: workout.name,
            workoutType: workout.workoutType,
            estimatedDurationMins: workout.estimatedDurationMins,
            coachingNote: workout.coachingNote,
            exercises: workout.exercises,
            contextSnapshot: context
        )

        return workout
    }

    private static func extractJSON(from text: String) -> String {
        // If response contains a JSON block, extract it
        if let start = text.range(of: "{"),
           let end = text.range(of: "}", options: .backwards),
           start.lowerBound < end.upperBound {
            return String(text[start.lowerBound...end.upperBound])
        }
        return text
    }
}

enum WorkoutParserError: LocalizedError {
    case invalidJSON

    var errorDescription: String? {
        "Kai returned an unexpected workout format. Please try again."
    }
}
